CREATE DATABASE bai1;

use bai1;

CREATE TABLE LoaiSanPham(
	MaLoaiSP INT PRIMARY KEY,
    TenLoaiSP VARCHAR(60) CHARACTER SET UTF8MB4
);

CREATE TABLE SanPham(
	MaSP INT PRIMARY KEY,
    TenSP VARCHAR(60) CHARACTER SET UTF8MB4,
    NhaSanXuat VARCHAR(100) CHARACTER SET UTF8MB4,
    MaLoaiSP INT,
    FOREIGN KEY (MaLoaiSP) REFERENCES LoaiSanPham(MaLoaiSP)
);