package layout;

import database.Database;
import java.awt.Font;
import java.sql.Connection;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.Sach;

public class MainLayout extends javax.swing.JFrame {
    private JFrame frame;
	private JTextField textField;
	private JLabel lblTnSch;
	private JTextField textField_1;
	private JLabel lblSTrang;
	private JTextField textField_2;
	private JLabel lblMTcGi;
	private JTextField textField_3;
	private JLabel lblSTrang_1;
	private JTextField textField_4;
	private JLabel lblSTrang_2;
	private JTextField textField_5;
	private JLabel lblSTrang_3;
	private JTextField textField_6;
	private JTable table;
    /**
     * Creates new form MainLayout
     */
    public MainLayout() throws SQLException {
        initComponents();
        DefaultTableModel modelSach = (DefaultTableModel) tblSach.getModel();
        Object[] rowData = new Object[7];
        ArrayList<Sach> list = getData();
        for (int i = 0; i < list.size(); i++) {
            Sach temp = list.get(i);
            rowData[0] = temp.getMaSach();
            rowData[1] = temp.getTuSach();
            rowData[2] = temp.getSoTrang();
            rowData[3] = temp.getMaTacGia();
            rowData[4] = temp.getNamXB();
            rowData[5] = temp.getTuKhoa();
            rowData[6] = temp.getNXB();
            modelSach.addRow(rowData);
        }
    }
    public ArrayList<Sach> getData() throws SQLException{
        ArrayList<Sach> arr = new ArrayList<>();
        Connection conn = (Connection) Database.getConnection();
        Statement stm = (Statement) conn.createStatement();
        java.sql.ResultSet rs = stm.executeQuery("select * from tblsach");
        while(rs.next()){
            Sach ele = new Sach(rs.getString(1),rs.getString(2),rs.getInt(3),rs.getString(4),rs.getInt(5),rs.getString(6),rs.getString(7));
            arr.add(ele);
        }
        return arr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblSach = new javax.swing.JTable();
        btnTimKiem = new javax.swing.JButton();
        txtSearch = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã sách", "Tủ sách", "Số trang", "Mã Tác Giả", "Năm xuất bản", "Từ khoá", "Nhà xuất bản"
            }
        ));
        jScrollPane1.setViewportView(tblSach);

        btnTimKiem.setText("Tìm kiếm");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addGroup(layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(btnTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(121, 121, 121)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 242, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTimKiem)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 327, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainLayout.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MainLayout().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(MainLayout.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    /**
	 * Initialize the contents of the frame.
	 */
	private void initialize() {
		frame = new JFrame();
		frame.setBounds(100, 100, 706, 721);
		frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frame.getContentPane().setLayout(null);
		
		textField = new JTextField();
		textField.setBounds(312, 51, 176, 19);
		frame.getContentPane().add(textField);
		textField.setColumns(10);
		
		JLabel lblNewLabel = new JLabel("M\u00E3 s\u00E1ch :\r\n");
		lblNewLabel.setFont(new Font("Tahoma", Font.PLAIN, 14));
		lblNewLabel.setBounds(127, 52, 86, 13);
		frame.getContentPane().add(lblNewLabel);
		
		lblTnSch = new JLabel("T\u1EF1a \u0111\u1EC1 s\u00E1ch :\r\n");
		lblTnSch.setFont(new Font("Tahoma", Font.PLAIN, 14));
		lblTnSch.setBounds(127, 101, 110, 13);
		frame.getContentPane().add(lblTnSch);
		
		textField_1 = new JTextField();
		textField_1.setColumns(10);
		textField_1.setBounds(312, 101, 176, 19);
		frame.getContentPane().add(textField_1);
		
		lblSTrang = new JLabel("S\u1ED1 trang :\r\n");
		lblSTrang.setFont(new Font("Tahoma", Font.PLAIN, 14));
		lblSTrang.setBounds(127, 154, 110, 19);
		frame.getContentPane().add(lblSTrang);
		
		textField_2 = new JTextField();
		textField_2.setColumns(10);
		textField_2.setBounds(312, 156, 176, 19);
		frame.getContentPane().add(textField_2);
		
		lblMTcGi = new JLabel("M\u00E3 t\u00E1c gi\u1EA3 :\r\n");
		lblMTcGi.setFont(new Font("Tahoma", Font.PLAIN, 14));
		lblMTcGi.setBounds(127, 213, 86, 13);
		frame.getContentPane().add(lblMTcGi);
		
		textField_3 = new JTextField();
		textField_3.setColumns(10);
		textField_3.setBounds(312, 212, 176, 19);
		frame.getContentPane().add(textField_3);
		
		lblSTrang_1 = new JLabel("N\u0103m xu\u1EA5t b\u1EA3n");
		lblSTrang_1.setFont(new Font("Tahoma", Font.PLAIN, 14));
		lblSTrang_1.setBounds(127, 258, 121, 13);
		frame.getContentPane().add(lblSTrang_1);
		
		textField_4 = new JTextField();
		textField_4.setColumns(10);
		textField_4.setBounds(312, 257, 176, 19);
		frame.getContentPane().add(textField_4);
		
		lblSTrang_2 = new JLabel("Nh\u00E0 xu\u1EA5t b\u1EA3n ;\r\n");
		lblSTrang_2.setFont(new Font("Tahoma", Font.PLAIN, 14));
		lblSTrang_2.setBounds(127, 315, 121, 13);
		frame.getContentPane().add(lblSTrang_2);
		
		textField_5 = new JTextField();
		textField_5.setColumns(10);
		textField_5.setBounds(312, 314, 176, 19);
		frame.getContentPane().add(textField_5);
		
		lblSTrang_3 = new JLabel("M\u00F4 t\u1EA3 s\u00E1ch :\r\n");
		lblSTrang_3.setFont(new Font("Tahoma", Font.PLAIN, 14));
		lblSTrang_3.setBounds(127, 374, 121, 13);
		frame.getContentPane().add(lblSTrang_3);
		
		textField_6 = new JTextField();
		textField_6.setColumns(10);
		textField_6.setBounds(312, 373, 176, 19);
		frame.getContentPane().add(textField_6);
		
		table = new JTable();
		table.setBounds(31, 599, 624, -157);
		frame.getContentPane().add(table);
	}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTimKiem;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblSach;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
